development: &default
  adapter: mysql2
  database: <%= ENV.fetch('MYSQL_DATABASE') %>
  host: <%= ENV.fetch('DATABASE_HOST') %>
  port: 3306
  username: <%= ENV.fetch('MYSQL_USER') %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') %>
  encoding: utf8
  timeout: 5000
  pool: 10

test:
  <<: *default
  database: etmodel_test

production:
  <<: *default
  database: etmodel_production

staging:
  <<: *default
  database: etmodel_staging
